package vectorforge

import "strings"

const (
	jobStatusPending    = "pending"
	jobStatusProcessing = "processing"
	jobStatusDone       = "done"
	jobStatusError      = "error"

	embeddingKindImage = "image"
	embeddingKindText  = "text"
)

type lookupRequest struct {
	Kind   string   `json:"kind"`
	Hashes []string `json:"hashes"`
}

type lookupResponse struct {
	Status map[string]string `json:"status"`
}

type uploadResponse struct {
	Status string `json:"status"`
	JobID  int64  `json:"job_id,omitempty"`
}

// QueueJob is a claimed job from queue.db.
type QueueJob struct {
	ID         int64
	FileHash   string
	Kind       string
	PayloadRef string
	Attempts   int
}

// JobRequest is a queue insertion request generated by upload API.
type JobRequest struct {
	FileHash   string
	Kind       string
	PayloadRef string
}

// EnqueueResult reports queue persistence outcome to uploader.
type EnqueueResult struct {
	JobID            int64
	StoredPayloadRef string
	ReusedQueue      bool
}

// WorkerResult carries worker inference output to the ingester.
type WorkerResult struct {
	Job         QueueJob
	VectorJSON  []byte
	WorkerError error
}

func normalizeEmbeddingKind(kind string) (string, bool) {
	switch strings.ToLower(strings.TrimSpace(kind)) {
	case embeddingKindImage:
		return embeddingKindImage, true
	case embeddingKindText:
		return embeddingKindText, true
	default:
		return "", false
	}
}
